name:        lab1
version:     0.1.0.0
synopsis:    SAssignment1 by Function programming
homepage:    https://github.com/CrocoRussian/fp_lab1#readme
license:     MIT 
author:      Your Name
maintainer:  mk.spbkiselev@gmail.com
copyright:   2025 Your Name
category:    Development  

extra-source-files:
- README.md
- LICENSE

ghc-options: -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
tests:
  your-project-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base
      - hspec
