name: functional-languages-lab
version: 0.1.0.0
github: yourname/fp_lab1
license: MIT
author: Croco
maintainer: you@example.com
extra-source-files: []

ghc-options:
  - -Wall

dependencies:
  - base >= 4.14 && < 5

library:
  source-dirs: src

executables:
  functional-languages-lab-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - functional-languages-lab

tests:
  unit:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
    dependencies:
      - base
      - HUnit
      - functional-languages-lab