
resolver: lts-22.0 

packages:
- .  

extra-deps: []

flags: {}  

extra-package-dbs: []  

ghc-options:
  "$locals": -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wmissing-export-lists -Wmissing-home-modules -Wpartial-fields -Wredundant-constraints


tests:
  your-project-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts
    dependencies:
      - base
      - hspec
