name: Haskell CI
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/*"
      - "**/*.hs"
      - "**/*.cabal"
      - "stack.yaml"
      - "package.yaml"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/*"
      - "**/*.hs"
      - "**/*.cabal"
      - "stack.yaml"
      - "package.yaml"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.8.1' 
          enable-stack: true
          stack-version: 'latest'

      - name: Cache Stack dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}
            ${{ runner.os }}-stack

      - name: Install dependencies
        run: stack build --only-dependencies --test

      - name: Build project
        run: stack build

      - name: Run tests
        run: stack test
        env:
          STACK_YAML: stack.yaml

      - name: Check code formatting (optional)
        run: stack exec ormolu -- --mode check $(find . -name '*.hs')
